#!/bin/sh -eu
cd "$(dirname -- "$0")"

"${CC-c99}" ${CFLAGS-} ${LDFLAGS-} -o update update.c

echo 1.."$(printf '%.0s\n' tests/t* | wc -l)"

failures=0
index=0

for test in tests/t*
do
	export TMPDIR

	TMPDIR=$(mktemp -d)
	tmpout=$(mktemp)
	tmperr=$(mktemp)

	if "$test" </dev/null >"$tmpout" 2>"$tmperr"
	then
		echo ok $((index += 1)) - "$test"
	else
		echo not ok $((index += 1)) - "$test"
		: $((failures += 1))

		sed -e 's/^/# [STDOUT] /' -- "$tmpout"
		sed -e 's/^/# [STDERR] /' -- "$tmperr"
	fi

	rm -r -- "$TMPDIR"
	unset TMPDIR
done

exit "$failures"
