#!/bin/sh -eu
canary=$(mktemp -u)
touch -t 201601010000 -- "${prereq=$(mktemp)}"
touch -t 200009130000 -- "${target=$(mktemp)}"
./update -p "$prereq" -t "$target" touch -- "$canary"
test -e "$canary"
