#!/bin/sh -eu
canary=$TMPDIR/tmp.$(LC_CTYPE=C tr -cd '[:alnum:]' </dev/urandom | head -c 10)
touch -t 201601010000 -- "${prereq=$(mktemp)}"
touch -t 200009130000 -- "${target=$(mktemp)}"
./update -p "$prereq" -t "$target" -- touch -- "$canary"
test -e "$canary"
