#!/bin/sh -eu
canary=$TMPDIR/tmp.$(LC_CTYPE=C tr -cd '[:alnum:]' </dev/urandom | head -c 10)
touch -t 201601010000 -- "${prereq1=$(mktemp)}"
prereq2=
touch -t 200009130000 -- "${target=$(mktemp)}"
if ./update -p "$prereq1" -t "$target" -p "$prereq2" touch -- "$canary"
then
	exit 1
fi
! test -e "$canary"
exit 0
