#!/bin/sh -eu
export LC_CTYPE=C
canary=$TMPDIR/tmp.$(tr -cd '[:alnum:]' </dev/urandom | fold -w10 | head -n1)
touch -t 200106060000 -- "${prereq=$(mktemp)}"
touch -t 197703300000 -- "${target1=$(mktemp)}"
touch -t 200112040000 -- "${target2=$(mktemp)}"
./update -p "$prereq" -t "$target1" -t "$target2" touch -- "$canary"
test -e "$canary"
