#!/bin/sh -eu
export LC_CTYPE=C
canary=$TMPDIR/tmp.$(tr -cd '[:alnum:]' </dev/urandom | fold -w10 | head -n1)
touch -t 201601010000 -- "${prereq=$(mktemp)}"
./update -p "$prereq" touch -- "$canary"
test ! -e "$canary"
