#!/bin/sh -eu
canary=$(mktemp -u)
touch -t 200103300840 -- "${prereq=$(mktemp)}"
touch -t 200103300840 -- "${target=$(mktemp)}"
./update -p "$prereq" -t "$target" touch -- "$canary"
test -e "$canary"
